services:
  toggl-webapp:
    build: .
    container_name: toggl-app
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - nginx_net
    expose:
      - "80"

networks:
  nginx_net:
    name: nginx_net
    external: true